# Generated by Django 6.0.1 on 2026-01-31 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taqdimot_app', '0003_remove_workusage_user_delete_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('method', models.CharField(choices=[('payme', 'Payme'), ('manual', 'Manual')], help_text='Payment method', max_length=10)),
                ('status', models.BooleanField(default=False, help_text='Payment confirmed')),
                ('receipt_image', models.ImageField(blank=True, help_text='Receipt image for manual payment', null=True, upload_to='payments/receipts/')),
                ('verified_by_ai', models.BooleanField(default=False, help_text='Whether the receipt was verified by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Date when payment was confirmed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='taqdimot_app.user')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('referat', 'Referat'), ('mustaqil', 'Mustaqil ish')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='How much balance was used', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='taqdimot_app.user')),
            ],
            options={
                'db_table': 'work_usages',
                'ordering': ['-created_at'],
            },
        ),
    ]
