# Generated by Django 6.0.1 on 2026-01-10 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat ID', unique=True)),
                ('username', models.CharField(blank=True, help_text='Telegram username', max_length=150, null=True)),
                ('first_name', models.CharField(help_text='Telegram first name', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Telegram last name', max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('method', models.CharField(choices=[('payme', 'Payme'), ('manual', 'Manual')], help_text='Payment method', max_length=10)),
                ('status', models.BooleanField(default=False, help_text='Payment confirmed')),
                ('receipt_image', models.ImageField(blank=True, help_text='Receipt image for manual payment', null=True, upload_to='payments/receipts/')),
                ('verified_by_ai', models.BooleanField(default=False, help_text='Whether the receipt was verified by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Date when payment was confirmed', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='taqdimot_app.user')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
