# Generated by Django 6.0.1 on 2026-01-31 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taqdimot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('referat', 'Referat'), ('mustaqil', 'Mustaqil ish')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='How much balance was used', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='taqdimot_app.user')),
            ],
            options={
                'db_table': 'work_usages',
                'ordering': ['-created_at'],
            },
        ),
    ]
