# Generated by Django 6.0.1 on 2026-01-31 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taqdimot_app', '0002_workusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workusage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='WorkUsage',
        ),
    ]
