# Generated by Django 6.0.1 on 2026-02-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taqdimot_app', '0003_remove_workusage_user_delete_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='ppt_templates/')),
                ('preview', models.ImageField(upload_to='previews/')),
            ],
        ),
    ]
