services:
  edumaster_db:
    image: postgres:17
    container_name: edumaster-db
    restart: always
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - edumaster_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  edumaster_web:
    build: .
    container_name: edumaster-web
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - edumaster_media:/app/media
      - edumaster_static:/app/staticfiles
    depends_on:
      edumaster_db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/admin/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

  edumaster_bot:
    build: .
    container_name: edumaster-bot
    restart: always
    volumes:
      - .:/app
    depends_on:
      edumaster_db:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: ["/app/entrypoint-bot.sh"]

volumes:
  edumaster_postgres_data:
  edumaster_media:
  edumaster_static: